runtime: python
env: flex


# Define los manejadores de solicitudes
handlers:
- url: /.*
  script: auto

# Variables de entorno
env_variables:
  GOOGLE_CLOUD_PROJECT: "pi1h-413301"
  GOOGLE_APPLICATION_CREDENTIALS: "C:/Users/LENOVO/AppData/Roaming/gcloud/application_default_credentials.json"

# Configuración opcional para la versión flexible

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5